global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.alertmanager.fr:465

route:
  group_by: ['alerting_rules']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'vincent.lrr@gmail.com'
    from: 'alertmanager.dlc'
    smarthost: in-v3.mailjet.com:2525
    auth_username: 'beedc068b9ce7d2ab46ede048f2fb65a'
    auth_password: 'LKn1jgxtMWyCSRXwo4Mp'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
